### ISSUE TITLE
Installation documentation link is broken

### ISSUE THREAD

**Issue by ul8** [BarrelStrength/PhpStorm-Live-Templates-Twig-Extended#1]
New link: https://www.jetbrains.com/help/webstorm/tuning-the-ide.html#config-directory

(same applies to https://github.com/BarrelStrength/PhpStorm-Live-Templates-Craft-CMS)

**Comment by BenParizek** [comment]
@ul8 Thanks. I'm a bit late to close this out but I believe this was addressed a while ago when we updated the installation rec to use the Settings Repository:
https://github.com/barrelstrength/PhpStorm-Live-Templates-Twig-Extended/commit/8728cdbf4444dcb04f086e892f04b77bff505b45

Please re-open if anything else comes up.
